environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    ANT_HOME: C:\ant

  matrix:
    - PYTHON: "C:\\Miniconda"
      JAVA_HOME: "C:\\Program Files (x86)\\Java\\jdk1.8.0"

    - PYTHON: "C:\\Miniconda-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

    - PYTHON: "C:\\Miniconda3"
      JAVA_HOME: "C:\\Program Files (x86)\\Java\\jdk1.8.0"

    - PYTHON: "C:\\Miniconda3-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

    - PYTHON: "C:\\cygwin\\usr\\bin"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

    - PYTHON: "C:\\cygwin64\\usr\\bin"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

install:
  # install apache ant
  - "powershell ./appveyor/install.ps1"

  # use python from build matrix, add ant path.
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\ant\\bin;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "where python"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "pip install -r test-requirements.txt numpy pytest setuptools"

  - "ant -f test\\build.xml"
  # Build the compiled extension and run the project tests
  - "python setup.py install"
build: false # Not a C# project, build stuff at the test step instead.

test_script:
  # run testsuite and upload test results to AppVeyor; return exit code of testsuite
  #- "powershell ./appveyor/runTestsuite.ps1"
  - pytest test/jpypetest --xunit-xml=xunit.xml

after_test:
  # upload results to AppVeyor
  - powershell "$wc = New-Object 'System.Net.WebClient'; \
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit.xml)) "