package:
  name: "jpype"
  version: "dev"

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - numpy x.x
    - python
    - setuptools

  run:
    - numpy x.x
    - python

test:
  requires:
    - mock
    - pytest
    - pytest-faulthandler
  files:
    - compile.py
  source_files:
    - test/*
    - setup.cfg

  imports:
    - jpype
  commands:
    - python compile.py --input_dir=test --output_dir=test/harness
    - pytest -vv test/jpypetest
